const CONFIG = {
  photos: [
    { src: "01-Textil-Sheii-Cobre-y-Fibra-de-Platano.jpg", title: "Textil Sheii, Cobre y Fibra de Platano", category: "General" },
    { src: "5. Tree of Life Lighting.MP4", title: "Verdi Showroom", category: "General" },
    { src: "Tree Spinning.MP4", title: "El Arbol de la vida de VERDI", category: "General" },
    { src: "02-El-Arbol-de-la-Vida-de-Verdi.JPG", title: "El Arbol de la Vida de Verdi", category: "General" },
    { src: "03-Tomás-y-el-Árbol-de-la-Vida.JPG", title: "Tomás y el Árbol de la Vida", category: "General" },
    { src: "04-Planta-de-Fique-y-Don-Anselmo-Curiti-Col.JPG", title: "Planta de Fique y Don Anselmo, Curiti, Colombia", category: "General" },
    { src: "05-Proceso-Extracción-Fique.JPG", title: "Proceso Extracción Fique", category: "General" },
    { src: "06-Tejedura-en-Telar-el-taller-de-Verdi.JPG", title: "Tejedura en Telar, el taller de Verdi", category: "General" },
    { src: "07-Tapete-Casablanca-Acero-y-Fique.JPG", title: "Tapete Casablanca, Acero y Fique", category: "General" },
    { src: "08-Borde-Flecos-Acero-y-Fique.JPG", title: "Borde Flecos, Acero y Fique", category: "General" },
    { src: "09-Tejeduria-en-Crochet-el-Taller-de-Verdi.MOV", title: "Tejeduria en Crochet, el Taller de Verdi", category: "General" },
    { src: "10-Tapetes-Casablanca-100pct-Cobre.JPG", title: "Tapetes Casablanca, 100% Cobre", category: "General" },
    { src: "11-Camino-Casablanca-100pct-Cobre.JPG", title: "Camino Casablanca, 100% Cobre", category: "General" },
    { src: "12-Flecos-100pct-Cobre.jpg", title: "Flecos 100% Cobre", category: "General" },
    { src: "13-Entrada-showroom-Verdi-Bogota.jpg", title: "Entrada showroom Verdi, Bogota", category: "General" },
    { src: "14-Textil-Techo-250-KG-de-Cobre.JPG", title: "Textil Techo, 250 KG de Cobre", category: "General" },
    { src: "15-Tapete-Casablanca-en-Telar.JPG", title: "Tapete Casablanca en Telar", category: "General" },
    { src: "16-Tapete-Casablanca-Verde-Olica-y-Cobre.JPG", title: "Tapete Casablanca Verde Olica y Cobre", category: "General" },
    { src: "17-Tapete-Casablanca-Verde-Oliva-y-Cobre.JPG", title: "Tapete Casablanca Verde Oliva y Cobre", category: "General" },
    { src: "18-Tapete-Luma-Alpaca-Fique-y-Cobre-Soho-NY.jpg", title: "Tapete Luma, Alpaca, Fique y Cobre, Soho, NYC", category: "General" },
    { src: "19-Tapete-Luma-Alpaca-Fique-y-Cobre.JPG", title: "Tapete Luma, Alpaca, Fique, y Cobre", category: "General" },
    { src: "20-Tapete-Meseta-Alpaca-y-Fique-Miami.JPG", title: "Tapete Meseta, Alpaca y Fique, Miami", category: "General" },
    { src: "21-Tapete-Meseta-Alpaca-y-Fique.jpg", title: "Tapete Meseta, Alpaca y Fique", category: "General" },
    { src: "22-Tapete-Rombos-Medianos-Alpaca-y-Cobre-NY.JPG", title: "Tapete Rombos Medianos, Alpaca y Cobre, NYC", category: "General" },
    { src: "23-Rombos-Medianos-Alpaca-y-Cobre.JPG", title: "Rombos Medianos, Alpaca y Cobre", category: "General" },
    { src: "24-Tapete-Axxis-en-Degrade-Cobre-Acero-Fiqu.JPG", title: "Tapete Axxis en Degrade, Cobre, Acero, Fique Verde Amazonas", category: "General" },
    { src: "25-Tapete-Casablanca-en-Degrade-Cobre-Acero.JPG", title: "Tapete Casablanca en Degrade, Cobre, Acero, Fique Verde Amazonas", category: "General" },
    { src: "26-Tapete-Casablanca-en-Degrade-Cobre-Acero.JPG", title: "Tapete Casablanca en Degrade, Cobre, Acero, Fique Verde Amazonas", category: "General" },
    { src: "27-Tapete-Casablanca-Acero-y-Fique-Venezia-.JPG", title: "Tapete Casablanca Acero y Fique, Venezia, Italia", category: "General" },
    { src: "28-Proceso-Bordes-Taller-de-Verdi.MOV", title: "Proceso Bordes, Taller de Verdi", category: ["General","Art"] },
    { src: "29-Tejeduria-en-Crochet-Ooro-Jasasi.JPG", title: "Tejeduria en Crochet, Ooro Jasasi", category: ["General","Art"] },
    { src: "30-Mailin-Tejeduria-en-Crochet.JPG", title: "Mailin, Tejeduria en Crochet", category: ["General","Art"] },
    { src: "31-Ooro-Jasai-Verdi-Showroom.JPG", title: "Ooro Jasai, Verdi Showroom", category: ["General","Art"] },
    { src: "32-Verdi-x-Cartier.JPG", title: "Verdi x Cartier", category: ["General","Art"] },
    { src: "33-Tejeduria-EL-Ocaso-Cartier.JPG", title: "Tejeduria, EL Ocaso, Cartier", category: ["General","Art"] },
    { src: "34-Tomás-y-El-Ocaso-Cartier.JPG", title: "Tomás y El Ocaso, Cartier", category: ["General","Art"] },
    { src: "35-El-Ocaso-Cartier.JPG", title: "El Ocaso, Cartier", category: ["General","Art"] },
    { src: "36-Tiempo-Tejeduria-El-Ocaso-Cartier.JPG", title: "Tiempo Tejeduria, El Ocaso, Cartier", category: ["General","Art"] },
    { src: "37-La-Macorina-Design-Miami.JPG", title: "La Macorina, Design Miami", category: ["General","Art"] },
    { src: "38-La-Macorina-Tomas-Vera.JPG", title: "La Macorina, Tomas Vera", category: ["General","Art"] },
    { src: "39-La-Macorina-Cumare-Nylon-y-Plumas.JPG", title: "La Macorina, Cumare, Nylon, y Plumas", category: ["General","Art"] },
    { src: "40-La-Macorina-Design-Miami.mov", title: "La Macorina, Design Miami", category: "General" },
    { src: "41-El-Ottoman-de-Verdi.JPG", title: "El Ottoman de Verdi", category: "General" },
    { src: "42-El-Ottoman-Design-Week-Republica-Dominic.jpg", title: "El Ottoman, Design Week Republica Dominicana", category: "General" },
    { src: "43-Sol-Cobre-y-Paja.JPG", title: "Sol, Cobre y Paja", category: ["General","Art"] },
    { src: "44-Sol-Oro-y-Plaja-Osaka-Bogota.JPG", title: "Sol, Oro y Plaja, Osaka, Bogota", category: ["General","Art"] },
    { src: "45-Sol-Oro-y-Paja.JPG", title: "Sol, Oro y Paja", category: ["General","Art"] },
    { src: "46-Coleccion-AES-Fibra-de-Platano-y-Laton.JPG", title: "Coleccion AES, Fibra de Platano y Laton", category: "General" },
    { src: "47-Coleccion-AES.JPG", title: "Coleccion AES", category: "General" },
    { src: "48-AES-Alpaca-y-Laton.JPG", title: "AES, Alpaca y Laton", category: "General" },
    { src: "49-Modelo-a-Escala-AES.JPG", title: "Modelo a Escala, AES", category: "General" },
    { src: "50-AES-Crin-de-Caballo-y-Laton.jpg", title: "AES, Crin de Caballo y Laton", category: "General" },
    { src: "51-Tapete-Dau-Acero-y-Fique-Corte-Custom.JPG", title: "Tapete Dau, Acero y Fique, Corte Custom", category: "General" },
    { src: "52-Tapete-Dau-Acero-y-Fique.JPG", title: "Tapete Dau, Acero y Fique", category: "General" },
    { src: "53-Tapete-Dau-Acero-y-Fique-Chicago.JPG", title: "Tapete Dau, Acero y Fique, Chicago", category: "General" },
    { src: "54-Union-Tapete-Susu-Alpaca-y-Cobre.JPG", title: "Union, Tapete Susu, Alpaca y Cobre", category: "General" },
    { src: "55-Amangiri-Utah.jpg", title: "Amangiri, Utah", category: "General" },
    { src: "56-Tomas-Installin-Verdis-Tree-of-Life.jpg", title: "Tomas, Installin Verdis Tree of Life", category: "General" },
    { src: "57-Tapete-Rombos-Turquesa-Claro-y-Cobre.JPG", title: "Tapete Rombos Turquesa Claro y Cobre", category: "General" },
    { src: "58-Tree-of-Life-Install-Amangiri.jpg", title: "Tree of Life Install, Amangiri", category: "General" },
    { src: "59-Tejeduria-Tapete-La-Coral.PNG", title: "Tejeduria, Tapete La Coral", category: "General" },
    { src: "60-Tapete-La-Coral-Los-Angeles.JPG", title: "Tapete La Coral, Los Angeles", category: "General" },
    { src: "61-Tapete-La-Coral-Los-Angeles.JPG", title: "Tapete La Coral, Los Angeles", category: "General" },
    { src: "62-Tapete-Tatami-Mix-Fique-Acero-y-Cobre.jpg", title: "Tapete Tatami Mix, Fique, Acero y Cobre", category: "General" },
    { src: "63-Portdada-Revista-Axxis-1997.JPG", title: "Portdada Revista Axxis, 1997", category: "General" },
    { src: "64-Carlos-Vera-Dieppa---VERDI.jpg", title: "Carlos Vera Dieppa - VERDI", category: "General" },
    { src: "65-Carlos-Vera-Dieppa.JPG", title: "Carlos Vera Dieppa", category: "General" },
    { src: "66-VERDI-Airlines.JPG", title: "VERDI Airlines", category: "General" },
    { src: "67-Libro-VERDI.JPG", title: "Libro VERDI", category: "General" },
    { src: "68-Tapete-Tatami-Alpaca-y-Fique-Bogota.JPG", title: "Tapete Tatami, Alpaca y Fique, Bogota", category: "General" },
    { src: "69-Tapete-Tatami-CDMX.JPG", title: "Tapete Tatami, CDMX", category: "General" },
    { src: "70-Tapete-Tatami-CDMX.JPG", title: "Tapete Tatami, CDMX", category: "General" },
    { src: "71-Chic-by-Accident-Expo.JPG", title: "Chic by Accident Expo", category: "General" },
    { src: "72-Susu-Crin-de-Caballo-y-Cobre.JPG", title: "Susu, Crin de Caballo y Cobre", category: "General" },
    { src: "73-Kanaspi-Chich-by-Accident.JPG", title: "Kanaspi, Chich by Accident", category: "General" },
    { src: "74-AES-Chic-by-Accident.JPG", title: "AES, Chic by Accident", category: "General" },
    { src: "75-Casablanca-Degrade-Chic-by-Accident.JPG", title: "Casablanca Degrade, Chic by Accident", category: "General" },
    { src: "76-Casablanca-Chic-by-Accident.JPG", title: "Casablanca, Chic by Accident", category: "General" },
    { src: "77-Luma-Verde-Amazonas-y-Cobre.JPG", title: "Luma, Verde Amazonas y Cobre", category: "General" },
    { src: "78-Casablanca-Alpaca-Cumare-y-Cobre.PNG", title: "Casablanca, Alpaca, Cumare y Cobre", category: "General" },
    { src: "163-Casablanca-Alpaca-Boucle-Cumare-Cobre.MOV", title: "Casablanca, Alpaca Boucle, Cumare, Cobre", category: "General" },
    { src: "79-Casablanca-Alpaca-Cumare-y-Cobre.JPG", title: "Casablanca, Alpaca, Cumare y Cobre", category: "General" },
    { src: "80-Axxis-Alpaca-Boucle-y-Cobre.JPG", title: "Axxis, Alpaca Boucle y Cobre", category: "General" },
    { src: "81-Axxis-Alpaca-Boucle-y-Cobre.JPG", title: "Axxis, Alpaca Boucle y Cobre", category: "General" },
    { src: "82-Liquid-and-Stain-Protection.JPG", title: "Liquid and Stain Protection", category: "General" },
    { src: "83-Outdoor-Luma-Stripes.JPG", title: "Outdoor Luma Stripes", category: "General" },
    { src: "84-Kanaspi-Outdoor.JPG", title: "Kanaspi Outdoor", category: "General" },
    { src: "85-Luma-Outdoor.jpg", title: "Luma Outdoor", category: "General" },
    { src: "Video Bailarina BALLET SONG v2.MP4", title: "La Bailarina", category: "General" },
    { src: "86-La-Bailarina.jpg", title: "La Bailarina", category: "General" },
    { src: "87-Textil-Plano-Fibra-de-Platano.JPG", title: "Textil Plano, Fibra de Platano", category: "General" },
    { src: "88-Textil-PAR-Fibra-de-Platano.JPG", title: "Textil PAR, Fibra de Platano", category: "General" },
    { src: "89-Textil-Sheii-Cumare-y-Cobre.JPG", title: "Textil Sheii, Cumare y Cobre", category: "General" },
    { src: "90-Cortinas-Fique.JPG", title: "Cortinas, Fique", category: "General" },
    { src: "91-Cortinas-Fique.JPG", title: "Cortinas Fique", category: "General" },
    { src: "92-Fabric-Collection-Verdi-Showroom.jpg", title: "Fabric Collection, Verdi Showroom", category: "General" },
    { src: "93-Sierra-Fibra-de-Platano-y-Seda-Bogota.JPG", title: "Sierra, Fibra de Platano y Seda, Bogota", category: "General" },
    { src: "94-Rombos-Fique-10pct-Cobre.JPG", title: "Rombos, Fique, 10% Cobre", category: "General" },
    { src: "95-Rug-Panels.JPG", title: "Rug Panels", category: "General" },
    { src: "96-Aluna-St-Regis-Punta-Mita.jpg", title: "Aluna, St Regis, Punta Mita", category: "General" },
    { src: "97-Kanaspi-St-Regis-Punta-Mita.jpg", title: "Kanaspi, St Regis, Punta Mita", category: "General" },
    { src: "98-Salone-del-Mobile-2025.JPG", title: "Salone del Mobile 2025", category: "General" },
    { src: "99-Salone-del-Mobile-2025.JPG", title: "Salone del Mobile 2025", category: "General" },
    { src: "100-Salone-del-Mobile-2024.JPG", title: "Salone del Mobile 2024", category: "General" },
    { src: "101-Kanaspi-Acero-y-Fique.jpg", title: "Kanaspi, Acero y Fique", category: "General" },
    { src: "102-Team-VERDI.JPG", title: "Team VERDI", category: "General" },
    { src: "103-Yare-Fique-Cobre-Panels.jpg", title: "Yare, Fique, Cobre Panels", category: "General" },
    { src: "104-Copper-Mesh.jpg", title: "Copper Mesh", category: "General" },
    { src: "105-Ika-Seda-y-Lino.JPG", title: "Ika, Seda y Lino", category: "General" },
    { src: "106-Ika-Seda-y-Lino.JPG", title: "Ika, Seda y Lino", category: "General" },
    { src: "107-Ika-Seda-y-Lino.JPG", title: "Ika, Seda y Lino", category: "General" },
    { src: "108-Ika-Fibra-de-Platano-y-seda.JPG", title: "Ika, Fibra de Platano y seda", category: "General" },
    { src: "109-Ika-Fibra-de-Platano-y-Cobre.MOV", title: "Ika, Fibra de Platano y Cobre", category: "General" },
    { src: "110-Ika-Fibra-de-Platano-y-Cobre.JPG", title: "Ika, Fibra de Platano y Cobre", category: "General" },
    { src: "111-Sierra-Fique-y-Cobre.JPG", title: "Sierra Fique y Cobre", category: "General" },
    { src: "112-Sierra-Fique-y-Cobre.JPG", title: "Sierra, Fique y Cobre", category: "General" },
    { src: "VIDEO-2026-01-28-13-28-24.MP4", title: "Sierra, Fique y Cobre", category: "General" },
    { src: "113-Yare-Acero.JPG", title: "Yare, Acero", category: "General" },
    { src: "114-Yare-Acero.JPG", title: "Yare, Acero", category: "General" },
    { src: "115-Yare-Acero.JPG", title: "Yare, Acero", category: "General" },
    { src: "116-Yare-Acero-Taller-de-Verdi.MP4", title: "Yare, Acero, Taller de Verdi", category: "General" },
    { src: "117-Tassel-Yare-y-Acero.JPG", title: "Tassel, Yare y Acero", category: "General" },
    { src: "118-Paneles-Yare-Cobre.JPG", title: "Paneles, Yare Cobre", category: "General" },
    { src: "119-Kuru-Riyadh-Saudi-Arabia.JPG", title: "Kuru, Riyadh, Saudi Arabia", category: "General" },
    { src: "120-Kuru-Riyadh-Saudi-Arabia.JPG", title: "Kuru, Riyadh, Saudi Arabia", category: "General" },
    { src: "121-Verdi-Showroom-CDMX.JPG", title: "Verdi Showroom CDMX", category: "General" },
    { src: "122-Textile-Architecture-Verdi-CDMX.JPG", title: "Textile Architecture, Verdi CDMX", category: "General" },
    { src: "123-Tatami-Mix-Acero-y-Fique.JPG", title: "Tatami Mix, Acero y Fique", category: "General" },
    { src: "124-Casablanca-Degrade.jpg", title: "Casablanca Degrade", category: "General" },
    { src: "125-Casablanca-Wallpiece.jpg", title: "Casablanca Wallpiece", category: "General" },
    { src: "126-Casablanca-Wallpiece-Verdi-CDMX.jpg", title: "Casablanca Wallpiece, Verdi CDMX", category: "General" },
    { src: "127-Milo.JPG", title: "Milo", category: "General" },
    { src: "128-Yare-Acero.JPG", title: "Yare Acero", category: "General" },
    { src: "129-Palma.JPG", title: "Palma", category: "General" },
    { src: "130-Palma-Nighttime.JPG", title: "Palma Nighttime", category: "General" },
    { src: "131-Palma-Daytime.JPG", title: "Palma Daytime", category: "General" },
    { src: "132-Plano-Fibra-de-Platano.JPG", title: "Plano, Fibra de Platano", category: "General" },
    { src: "133-Wallpaper-Fibra-de-Platano.JPG", title: "Wallpaper, Fibra de Platano", category: "General" },
    { src: "134-Wallpaper-Install.JPG", title: "Wallpaper Install", category: "General" },
    { src: "135-Baby-Alpaca-Panel.JPG", title: "Baby Alpaca Panel", category: "General" },
    { src: "136-Pillows-Copper-and-Alpaca.JPG", title: "Pillows, Copper and Alpaca", category: "General" },
    { src: "137-Pillows-Fique-y-Cobre.JPG", title: "Pillows, Fique y Cobre", category: "General" },
    { src: "138-Salone-del-Mobile-2022.JPG", title: "Salone del Mobile 2022", category: "General" },
    { src: "139-Salone-del-Mobile-Laberinto-Textil.JPG", title: "Salone del Mobile, Laberinto Textil", category: "General" },
    { src: "140-Tomás-Vera-Salone-del-Mobile.JPG", title: "Tomás Vera, Salone del Mobile", category: "General" },
    { src: "141-Textil-Fibra-de-Platano-y-Seda-Salone-de.JPG", title: "Textil Fibra de Platano y Seda, Salone del Mobile", category: "General" },
    { src: "142-Surcos-Ritz.jpg", title: "Surcos, Ritz", category: ["General","Art"] },
    { src: "143-Surcos-Cobre-y-Fique.JPG", title: "Surcos, Cobre y Fique", category: ["General","Art"] },
    { src: "144-Degrade.JPG", title: "Degrade", category: ["General","Art"] },
    { src: "145-Santuario-Install-One-and-Only-Mandarina.JPG", title: "Santuario Install, One and Only Mandarina", category: ["General","Art"] },
    { src: "146-Santurio-Install-One-and-Only-Mandarina.JPG", title: "Santurio Install One and Only Mandarina", category: ["General","Art"] },
    { src: "L1082911.mov", title: "Santuario, One and Only Mandarina", category: "General" },
    { src: "147-Mochila-Piñas-Cobre-y-Azul.JPG", title: "Mochila Piñas, Cobre y Azul", category: "General" },
    { src: "148-Hand-Weaving-Mochilas.MP4", title: "Hand Weaving Mochilas", category: "General" },
    { src: "149-Mochila-Seashells-Oro-y-Plata.JPG", title: "Mochila Seashells, Oro y Plata", category: "General" },
    { src: "150-Mochila-kaia-Oro-y-Cobre.JPG", title: "Mochila kaia, Oro y Cobre", category: "General" },
    { src: "151-Mochila-Piñas-Oro-Esmeralda.JPG", title: "Mochila Piñas, Oro Esmeralda", category: "General" },
    { src: "152-Pineapple-Weave-Silk-and-Copper.jpg", title: "Pineapple Weave, Silk and Copper", category: "General" },
    { src: "153-Seashell-Weave.JPG", title: "Seashell Weave", category: "General" },
    { src: "154-Nido-Weave-Oro-y-Negro.JPG", title: "Nido Weave, Oro y Negro", category: "General" },
    { src: "155-Pride-Bag-Silver-Plated-Copper-and-Silk.JPG", title: "Pride Bag, Silver Plated Copper and Silk", category: "General" },
    { src: "156-Pineapple-Weave-Gold-and-Silk.JPG", title: "Pineapple Weave, Gold and Silk", category: "General" },
    { src: "157-Pineapple-Clutch.JPG", title: "Pineapple Clutch", category: "General" },
    { src: "158-Verdi-by-Johana-Ortiz.JPG", title: "Verdi by Johana Ortiz", category: "General" },
    { src: "159-Verdy-by-Johana-Ortiz.JPG", title: "Verdy by Johana Ortiz", category: "General" },
    { src: "VIDEO-2025-02-13-13-28-47.MP4", title: "FENDI x VERDI", category: "General" },
    { src: "160-Data-Sheet-1.JPG", title: "Data Sheet 1", category: "General" },
    { src: "161-Data-Sheet-2.JPG", title: "Data Sheet 2", category: "General" },
    { src: "162-Instagram.jpg", title: "Instagram", category: "General" }
  ]
};
