const CONFIG = {
  photos: [
    { src: "IMG_0770.jpg", title: "Textil Sheii, Cobre y Fibra de Platano", category: "General" },
    { src: "IMG_0013.JPG", title: "El Arbol de la Vida de Verdi", category: "General" },
    { src: "DSC07750.JPG", title: "Tomás y el Árbol de la Vida", category: "General" },
    { src: "DSC_8017.JPG", title: "Planta de Fique y Don Anselmo, Curiti, Colombia", category: "General" },
    { src: "IMG_0774.JPG", title: "Proceso Extracción Fique", category: "General" },
    { src: "DSC00573.JPG", title: "Tejedura en Telar, el taller de Verdi", category: "General" },
    { src: "IMG_0033.JPG", title: "Tapete Casablanca, Acero y Fique", category: "General" },
    { src: "IMG_0609.JPG", title: "Borde Flecos, Acero y Fique", category: "General" },
    { src: "Mexico Design Week.MOV", title: "Tejeduria en Crochet, el Taller de Verdi", category: "General" },
    { src: "IMG_2252.JPG", title: "Tapetes Casablanca, 100% Cobre", category: "General" },
    { src: "IMG_0023.JPG", title: "Camino Casablanca, 100% Cobre", category: "General" },
    { src: "T_M_Casablanca_MEM01_MEM01_08.jpg", title: "Flecos 100% Cobre", category: "General" },
    { src: "©monica-barreneche-verdi-design-showroom-17.jpg", title: "Entrada showroom Verdi, Bogota", category: "General" },
    { src: "DSC07223-2.JPG", title: "Textil Techo, 250 KG de Cobre", category: "General" },
    { src: "IMG_0626.JPG", title: "Tapete Casablanca en Telar", category: "General" },
    { src: "IMG_0025.JPG", title: "Tapete Casablanca Verde Olica y Cobre", category: "General" },
    { src: "IMG_0030.JPG", title: "Tapete Casablanca Verde Oliva y Cobre", category: "General" },
    { src: "DSC03228.jpg", title: "Tapete Luma, Alpaca, Fique y Cobre, Soho, NYC", category: "General" },
    { src: "I-1482(11).JPG", title: "Tapete Luma, Alpaca, Fique, y Cobre", category: "General" },
    { src: "IMG_7647.JPG", title: "Tapete Meseta, Alpaca y Fique, Miami", category: "General" },
    { src: "IMG_0772.jpg", title: "Tapete Meseta, Alpaca y Fique", category: "General" },
    { src: "IMG_7727.JPG", title: "Tapete Rombos Medianos, Alpaca y Cobre, NYC", category: "General" },
    { src: "IMG_0771.JPG", title: "Rombos Medianos, Alpaca y Cobre", category: "General" },
    { src: "L1041749.JPG", title: "Tapete Axxis en Degrade, Cobre, Acero, Fique Verde Amazonas", category: "General" },
    { src: "IMG_0042.JPG", title: "Tapete Casablanca en Degrade, Cobre, Acero, Fique Verde Amazonas", category: "General" },
    { src: "DSC00459.JPG", title: "Tapete Casablanca en Degrade, Cobre, Acero, Fique Verde Amazonas", category: "General" },
    { src: "IMG_0777.JPG", title: "Tapete Casablanca Acero y Fique, Venezia, Italia", category: "General" },
    { src: "Mexico Design Week 2.MOV", title: "Proceso Bordes, Taller de Verdi", category: "General" },
    { src: "IMG_0601.JPG", title: "Tejeduria en Crochet, Ooro Jasasi", category: "General" },
    { src: "DSC01744-Edit.JPG", title: "Mailin, Tejeduria en Crochet", category: "General" },
    { src: "IMG_0644.JPG", title: "Ooro Jasai, Verdi Showroom", category: "General" },
    { src: "8a1d1cec-102f-4dc3-96e2-30d0ec9f6481.JPG", title: "Verdi x Cartier", category: "General" },
    { src: "cdd974d1-7db8-44c3-9a45-647e1c1b9b6f.JPG", title: "Tejeduria, EL Ocaso, Cartier", category: "General" },
    { src: "6bec5d86-96e5-4b21-9b01-16fc63adae62.JPG", title: "Tomás y El Ocaso, Cartier", category: "General" },
    { src: "47d2c0fd-ac73-4830-ad17-154247311838.JPG", title: "El Ocaso, Cartier", category: "General" },
    { src: "4d4fdae1-8fa1-4c69-a0cb-1cea8b1f0123.JPG", title: "Tiempo Tejeduria, El Ocaso, Cartier", category: "General" },
    { src: "Libro_-80.JPG", title: "La Macorina, Design Miami", category: "General" },
    { src: "Libro_-81.JPG", title: "La Macorina, Tomas Vera", category: "General" },
    { src: "DSC01806.JPG", title: "La Macorina, Cumare, Nylon, y Plumas", category: "General" },
    { src: "C0007.mov", title: "La Macorina, Design Miami", category: "General" },
    { src: "9856aa0a-bea0-4e62-ab5d-f072ef67a373.JPG", title: "El Ottoman de Verdi", category: "General" },
    { src: "DSC07910.jpg", title: "El Ottoman, Design Week Republica Dominicana", category: "General" },
    { src: "DSC03892-Edit-Edit.JPG", title: "Sol, Cobre y Paja", category: "General" },
    { src: "IMG_7531.JPG", title: "Sol, Oro y Plaja, Osaka, Bogota", category: "General" },
    { src: "IMG_7532.JPG", title: "Sol, Oro y Paja", category: "General" },
    { src: "IMG_0358.JPG", title: "Coleccion AES, Fibra de Platano y Laton", category: "General" },
    { src: "IMG_0353.JPG", title: "Coleccion AES", category: "General" },
    { src: "IMG_0356.JPG", title: "AES, Alpaca y Laton", category: "General" },
    { src: "IMG_0361.JPG", title: "Modelo a Escala, AES", category: "General" },
    { src: "DSC_3546.jpg", title: "AES, Crin de Caballo y Laton", category: "General" },
    { src: "DSC_2228.JPG", title: "Tapete Dau, Acero y Fique, Corte Custom", category: "General" },
    { src: "DSC_2271.JPG", title: "Tapete Dau, Acero y Fique", category: "General" },
    { src: "ad9954d6-9fd9-47eb-88c5-789eebbe434b.JPG", title: "Tapete Dau, Acero y Fique, Chicago", category: "General" },
    { src: "VDI9832.JPG", title: "Union, Tapete Susu, Alpaca y Cobre", category: "General" },
    { src: "IMG_1927.jpg", title: "Amangiri, Utah", category: "General" },
    { src: "DSC01517.jpg", title: "Tomas, Installin Verdi´s Tree of Life", category: "General" },
    { src: "verdi-chingaza-photo©monica-barreneche-3.JPG", title: "Tapete Rombos Turquesa Claro y Cobre", category: "General" },
    { src: "DSC02171.jpg", title: "Tree of Life Install, Amangiri", category: "General" },
    { src: "NEW SLIDES BRIDGE HOUSE-05.PNG", title: "Tejeduria, Tapete La Coral", category: "General" },
    { src: "DSC06016.JPG", title: "Tapete La Coral, Los Angeles", category: "General" },
    { src: "DSC06017.JPG", title: "Tapete La Coral, Los Angeles", category: "General" },
    { src: "IMG_6532.jpg", title: "Tapete Tatami Mix, Fique, Acero y Cobre", category: "General" },
    { src: "001.JPG", title: "Portdada Revista Axxis, 1997", category: "General" },
    { src: "IMG_0017.jpg", title: "Carlos Vera Dieppa - VERDI", category: "General" },
    { src: "IMG_0009.JPG", title: "Carlos Vera Dieppa", category: "General" },
    { src: "8bfa8769-4f93-4609-9ff6-80fc8fd2e8b8.JPG", title: "VERDI Airlines", category: "General" },
    { src: "DSC03422.JPG", title: "Libro VERDI", category: "General" },
    { src: "VDI1529.JPG", title: "Tapete Tatami, Alpaca y Fique, Bogota", category: "General" },
    { src: "IMG_7793.JPG", title: "Tapete Tatami, CDMX", category: "General" },
    { src: "IMG_7754.JPG", title: "Tapete Tatami, CDMX", category: "General" },
    { src: "DSC04673.JPG", title: "Chic by Accident Expo", category: "General" },
    { src: "DSC_2188.JPG", title: "Susu, Crin de Caballo y Cobre", category: "General" },
    { src: "DSC04099.JPG", title: "Kanaspi, Chich by Accident", category: "General" },
    { src: "DSC04086.JPG", title: "AES, Chic by Accident", category: "General" },
    { src: "DSC04116.JPG", title: "Casablanca Degrade, Chic by Accident", category: "General" },
    { src: "DSC04077.JPG", title: "Casablanca, Chic by Accident", category: "General" },
    { src: "DSC00307.JPG", title: "Luma, Verde Amazonas y Cobre", category: "General" },
    { src: "Highland4K.00_01_34_19.Still007.PNG", title: "Casablanca, Alpaca, Cumare y Cobre", category: "General" },
    { src: "IMG_9278.JPG", title: "Casablanca, Alpaca, Cumare y Cobre", category: "General" },
    { src: "VDI3485.JPG", title: "Axxis, Alpaca Boucle y Cobre", category: "General" },
    { src: "VDI8131.JPG", title: "Axxis, Alpaca Boucle y Cobre", category: "General" },
    { src: "IMG_7533.JPG", title: "Liquid and Stain Protection", category: "General" },
    { src: "DSC7021-Edit.JPG", title: "Outdoor Luma Stripes", category: "General" },
    { src: "DSC04044.JPG", title: "Kanaspi Outdoor", category: "General" },
    { src: "DSC00407.jpg", title: "Luma Outdoor", category: "General" },
    { src: "DSC09014.jpg", title: "La Bailarina", category: "General" },
    { src: "IMG_0202.JPG", title: "Textil Plano, Fibra de Platano", category: "General" },
    { src: "IMG_0203.JPG", title: "Textil PAR, Fibra de Platano", category: "General" },
    { src: "IMG_8945.JPG", title: "Textil Sheii, Cumare y Cobre", category: "General" },
    { src: "IMG_1203.JPG", title: "Cortinas, Fique", category: "General" },
    { src: "DSC_2418.JPG", title: "Cortinas Fique", category: "General" },
    { src: "DSC_0909-3.jpg", title: "Fabric Collection, Verdi Showroom", category: "General" },
    { src: "Plantain Fiber and Silk Wall Panel.JPG", title: "Sierra, Fibra de Platano y Seda, Bogota", category: "General" },
    { src: "Rhombus-Fique.JPG", title: "Rombos, Fique, 10% Cobre", category: "General" },
    { src: "IMG_7646.JPG", title: "Rug Panels", category: "General" },
    { src: "St. Regis_HUBER Design_15.jpg", title: "Aluna, St Regis, Punta Mita", category: "General" },
    { src: "St. Regis_HUBER Design_20 (1).jpg", title: "Kanaspi, St Regis, Punta Mita", category: "General" },
    { src: "L1021899.JPG", title: "Salone del Mobile 2025", category: "General" },
    { src: "L1021898.JPG", title: "Salone del Mobile 2025", category: "General" },
    { src: "DSC02033.JPG", title: "Salone del Mobile 2024", category: "General" },
    { src: "DSC01548.jpg", title: "Kanaspi, Acero y Fique", category: "General" },
    { src: "DSC01442.JPG", title: "Team VERDI", category: "General" },
    { src: "VDI1697.jpg", title: "Yare, Fique, Cobre Panels", category: "General" },
    { src: "VDI1718.jpg", title: "Copper Mesh", category: "General" },
    { src: "IMG_0074.JPG", title: "Ika, Seda y Lino", category: "General" },
    { src: "DSC00591-Edit-Edit.JPG", title: "Ika, Seda y Lino", category: "General" },
    { src: "DSC00527.JPG", title: "Ika, Seda y Lino", category: "General" },
    { src: "DSC00125.JPG", title: "Ika, Fibra de Platano y seda", category: "General" },
    { src: "IMG_9653.MOV", title: "Ika, Fibra de Platano y Cobre", category: "General" },
    { src: "DSC_2286.JPG", title: "Ika, Fibra de Platano y Cobre", category: "General" },
    { src: "L1122866.JPG", title: "Sierra Fique y Cobre", category: "General" },
    { src: "L1122980.JPG", title: "Sierra, Fique y Cobre", category: "General" },
    { src: "IMG_0191.JPG", title: "Yare, Acero", category: "General" },
    { src: "IMG_0190.JPG", title: "Yare, Acero", category: "General" },
    { src: "IMG_0189 2.JPG", title: "Yare, Acero", category: "General" },
    { src: "CCB86040-5431-4457-805E-04CF1B717058.MP4", title: "Yare, Acero, Taller de Verdi", category: "General" },
    { src: "5E550F0A-1F04-4954-AA60-E6531EFFDF00.JPG", title: "Tassel, Yare y Acero", category: "General" },
    { src: "DSC06415.JPG", title: "Paneles, Yare Cobre", category: "General" },
    { src: "IMG_8141.JPG", title: "Kuru, Riyadh, Saudi Arabia", category: "General" },
    { src: "IMG_8148.JPG", title: "Kuru, Riyadh, Saudi Arabia", category: "General" },
    { src: "L1010434.JPG", title: "Verdi Showroom CDMX", category: "General" },
    { src: "L1010599.JPG", title: "Textile Architecture, Verdi CDMX", category: "General" },
    { src: "L1010379.JPG", title: "Tatami Mix, Acero y Fique", category: "General" },
    { src: "L1010393.jpg", title: "Casablanca Degrade", category: "General" },
    { src: "L1014144.jpg", title: "Casablanca Wallpiece", category: "General" },
    { src: "L1014196.jpg", title: "Casablanca Wallpiece, Verdi CDMX", category: "General" },
    { src: "L1010416.JPG", title: "Milo", category: "General" },
    { src: "L1010458.JPG", title: "Yare Acero", category: "General" },
    { src: "DSC00366.JPG", title: "Palma", category: "General" },
    { src: "DSC00356.JPG", title: "Palma Nighttime", category: "General" },
    { src: "DSC_2449.JPG", title: "Palma Daytime", category: "General" },
    { src: "Banana Shades 2.JPG", title: "Plano, Fibra de Platano", category: "General" },
    { src: "DSC_2319-Edit.JPG", title: "Wallpaper, Fibra de Platano", category: "General" },
    { src: "IMG_0769.JPG", title: "Wallpaper Install", category: "General" },
    { src: "IMG_0768.JPG", title: "Baby Alpaca Panel", category: "General" },
    { src: "IMG_7534.JPG", title: "Pillows, Copper and Alpaca", category: "General" },
    { src: "IMG_0620.JPG", title: "Pillows, Fique y Cobre", category: "General" },
    { src: "DSC06226.JPG", title: "Salone del Mobile 2022", category: "General" },
    { src: "IMG_1539.JPG", title: "Salone del Mobile, Laberinto Textil", category: "General" },
    { src: "DSC06373.JPG", title: "Tomás Vera, Salone del Mobile", category: "General" },
    { src: "DSC06422.JPG", title: "Textil Fibra de Platano y Seda, Salone del Mobile", category: "General" },
    { src: "013e7914-bfe6-47b5-8392-ae785f84de51.jpg", title: "Surcos, Ritz", category: "General" },
    { src: "9f2b3b4d-ac83-410b-9274-b369a94e8c90.JPG", title: "Surcos, Cobre y Fique", category: "General" },
    { src: "L1027496.JPG", title: "Degrade", category: "General" },
    { src: "L1082673.JPG", title: "Santuario Install, One and Only Mandarina", category: "General" },
    { src: "L1082747.JPG", title: "Santurio Install One and Only Mandarina", category: "General" },
    { src: "IMG_0650.JPG", title: "Mochila Piñas, Cobre y Azul", category: "General" },
    { src: "REEL PIÑAS_2.MP4", title: "Hand Weaving Mochilas", category: "General" },
    { src: "IMG_0231.JPG", title: "Mochila Seashells, Oro y Plata", category: "General" },
    { src: "IMG_0658.JPG", title: "Mochila kaia, Oro y Cobre", category: "General" },
    { src: "IMG_0598.JPG", title: "Mochila Piñas, Oro Esmeralda", category: "General" },
    { src: "IMG_0612.jpg", title: "Pineapple Weave, Silk and Copper", category: "General" },
    { src: "DSC01398.JPG", title: "Seashell Weave", category: "General" },
    { src: "IMG_0233.JPG", title: "Nido Weave, Oro y Negro", category: "General" },
    { src: "IMG_0675.JPG", title: "Pride Bag, Silver Plated Copper and Silk", category: "General" },
    { src: "IMG_0606.JPG", title: "Pineapple Weave, Gold and Silk", category: "General" },
    { src: "IMG_1263.JPG", title: "Pineapple Clutch", category: "General" },
    { src: "IMG_1265.JPG", title: "Verdi by Johana Ortiz", category: "General" },
    { src: "IMG_1266.JPG", title: "Verdy by Johana Ortiz", category: "General" },
    { src: "IMG_0336.JPG", title: "Data Sheet 1", category: "General" },
    { src: "IMG_0335.JPG", title: "Data Sheet 2", category: "General" },
    { src: "IMG_7837.jpg", title: "Instagram", category: "General" },
    { src: "IMG_9412.MOV", title: "Casablanca, Alpaca Boucle, Cumare, Cobre", category: "General" },
  ]
};